### ISSUE TITLE
time data '' does not match format '%Y%m%d' エラー

### ISSUE THREAD

**Issue by new-village** [new-village/nkparser#3]
race_id = `202201020801` で下記のエラーが発生する。
```
Traceback (most recent call last):
  File "/workspaces/nkcrawler/run.py", line 51, in <module>
    nkdata = nkparser.load(table_name, race_id)
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/load.py", line 29, in load
    return loader.exec()
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/load.py", line 69, in exec
    self.info = parse_text("race", self.text, self.entity_id)
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 18, in parse_text
    return parser.exec()
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 88, in exec
    kv5 = [{col["col_name"]: self._apply_post_func(col, rec) for col in self.columns} for rec in kv4]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 88, in <listcomp>
    kv5 = [{col["col_name"]: self._apply_post_func(col, rec) for col in self.columns} for rec in kv4]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 88, in <dictcomp>
    kv5 = [{col["col_name"]: self._apply_post_func(col, rec) for col in self.columns} for rec in kv4]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 63, in _apply_post_func
    val = self._call_functions(col, rec, "post_func")
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 70, in _call_functions
    return globals()[func_name](eval(args))
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/help.py", line 139, in fmt_date
    return dt.strptime(dt_str, "%Y%m%d").strftime('%Y-%m-%d')
  File "/opt/python/3.10.4/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/python/3.10.4/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y%m%d'
```

**Comment by new-village** [comment]
### 状況  
開催前のデータを取得しようとした場合、発送日を取得している `div.RaceList_Item03 a`が無いことが発覚
![image](https://user-images.githubusercontent.com/3105234/188255413-c7d072f0-3695-4729-bac9-157c2102d8ba.png)
