### ISSUE TITLE
日付のパース・エラー

### ISSUE THREAD

**Issue by new-village** [new-village/nkparser#6]
race_id = `202250030808` で下記のエラーが発生している。
```
Traceback (most recent call last):
  File "/workspaces/nkcrawler/run.py", line 51, in <module>
    result = nkparser.load("result", race['race_id'])
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/load.py", line 29, in load
    return loader.exec()
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/load.py", line 86, in exec
    self.info = parse_text("race_db", self.text, self.entity_id)
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 18, in parse_text
    return parser.exec()
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 88, in exec
    kv5 = [{col["col_name"]: self._apply_post_func(col, rec) for col in self.columns} for rec in kv4]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 88, in <listcomp>
    kv5 = [{col["col_name"]: self._apply_post_func(col, rec) for col in self.columns} for rec in kv4]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 88, in <dictcomp>
    kv5 = [{col["col_name"]: self._apply_post_func(col, rec) for col in self.columns} for rec in kv4]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 63, in _apply_post_func
    val = self._call_functions(col, rec, "post_func")
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 70, in _call_functions
    return globals()[func_name](eval(args))
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/help.py", line 146, in fmt_date
    return dt.strptime(dt_str, "%Y%m%d").strftime('%Y-%m-%d')
  File "/opt/python/3.10.4/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/python/3.10.4/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '20225003' does not match format '%Y%m%d'
```

**Comment by new-village** [comment]
地方競馬の場合、CSS Selector の場所が変わるために発生したエラー。
9a9cea147865b8ea7a80dd4304355393005982ec
