### ISSUE TITLE
`2020C8100404` ロード時のパースエラー

### ISSUE THREAD

**Issue by new-village** [new-village/nkparser#7]
```
result: 2020C8100404
Traceback (most recent call last):
  File "/workspaces/nkcrawler/run.py", line 54, in <module>
    result = nkparser.load("result", race['race_id'])
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/load.py", line 29, in load
    return loader.exec()
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/load.py", line 87, in exec
    self.table = parse_text("result", self.text, self.entity_id)
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 18, in parse_text
    return parser.exec()
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 84, in exec
    kv3 = [{col["col_name"]: self._apply_format(col, rec) for col in self.columns} for rec in kv2]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 84, in <listcomp>
    kv3 = [{col["col_name"]: self._apply_format(col, rec) for col in self.columns} for rec in kv2]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 84, in <dictcomp>
    kv3 = [{col["col_name"]: self._apply_format(col, rec) for col in self.columns} for rec in kv2]
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/parse.py", line 40, in _apply_format
    val = formatter(col["reg"], val, col["var_type"])
  File "/workspaces/nkcrawler/.venv/lib/python3.10/site-packages/nkparser/help.py", line 34, in formatter
    value = float(val) if val is not None else None
ValueError: could not convert string to float: '2:39'
```

**Comment by new-village** [comment]
エラーが発生している[ページ](https://db.netkeiba.com/race/2020C8100404/)。
![image](https://user-images.githubusercontent.com/3105234/189677262-0b1bf260-2e19-4bea-8bbe-fc08012dbc56.png)

**Comment by new-village** [comment]
`2:39:30` は `2:39.30` の typo であると判断してパースするロジックを追加。
